### ISSUE TITLE
Support for punycode@2.0.0

### ISSUE THREAD

**Issue by kasicka** [jviotti/unicode-length#2]
Hi, could you update your punycode dependency? It is breaking our builds in Fedora, plus it is bundled in latest Node.

**Comment by jviotti** [comment]
Hi @kasicka,

Sure, will definitely do. You caught me on a fly right now but will handle later today.

**Comment by jviotti** [comment]
Hi @kasicka ,

Sorry for the delay. I've just published v1.0.2. Let me know if I can help with anything else!
